name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build_type: ['Debug', 'Release']
        os: [windows-latest, ubuntu-latest, macos-latest]
        shared_libs: ['ON', 'OFF']

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux system dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev libgl-dev

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_SHARED_LIBS=${{matrix.shared_libs}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Install fp on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: f3d-app/install-mesa-windows-action@v1
      with:
        path: ${{github.workspace}}/build/tests/${{matrix.build_type}}

    - name: Test
      if: ${{ matrix.os != 'ubuntu-latest' }}
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}

    - name: Test Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      working-directory: ${{github.workspace}}/build
      run: ./tests/dpImApp_Test_Simple
